import { z } from "zod";
import { businessDateSchema, positiveMoneyWireSchema, uuidSchema } from "./common.js";
import { odometerSourceSchema } from "./lease-billing.js";

/** DM §9's `CHECK` on `expense.category` — the borne-by default matrix (UC §6.7) is keyed on this. */
export const expenseCategorySchema = z.enum([
  "fuel",
  "tolls",
  "fines",
  "cleaning",
  "tyres",
  "servicing",
  "repairs",
  "insurance",
  "licence",
  "crew_food",
  "permits",
  "office",
  "legal",
  "messaging",
  "other",
  // GAP-185/UC-106/UC §6.7: a loan payment's finance portion (INV-43) —
  // always `borne_by: 'us'` in every arrangement, generated by
  // domain/vehicle-loan.ts rather than entered through this form.
  "finance",
]);
export type ExpenseCategory = z.infer<typeof expenseCategorySchema>;

export const borneBySchema = z.enum(["us", "driver", "customer"]);
export type BorneBy = z.infer<typeof borneBySchema>;

/**
 * F-3.1/F-3.2/F-3.3, UC-60/UC-66. `vehicleId` absent means an overhead cost
 * (UC-66, INV-24) — never a required field pretending zero is a vehicle.
 * `borneBy`/`paidByUserId` are both defaulted server-side (UC §6.7's matrix,
 * "whoever is entering") and both overridable here — W-48/INV-27 keeps them
 * two separate questions, never derived from one another.
 *
 * GAP-224: the field set create and replace share — `createExpenseRequestSchema`
 * adds `replacesId` (GAP-60/D-16), `replaceExpenseRequestSchema` adds `reason`
 * (F-8.5) — split out once both existed, so the shared fields and their
 * comments live in one place rather than two copies drifting the way
 * `assert_period_open()`'s own hand-maintained array already has once
 * (CLAUDE.md → Writes).
 */
const expenseCommonFieldsSchema = z.object({
  vehicleId: uuidSchema.optional(),
  // F-5.2/F-5.4: a cost incurred on a charter, folded into that trip's own
  // P&L (UC-44) rather than only the vehicle's month — the trip and the
  // vehicle are not exclusive, so both may be set.
  tripId: uuidSchema.optional(),
  // F-3.4/UC-12: a repair cost attached to the incident container — entered
  // "as invoices arrive over following weeks" against an already-open
  // incident, not exclusive with tripId or vehicleId.
  incidentId: uuidSchema.optional(),
  category: expenseCategorySchema,
  // GAP-177: a cost of nothing is not a cost. Zero here is a mis-entry.
  amountMinor: positiveMoneyWireSchema,
  spentOn: businessDateSchema,
  borneBy: borneBySchema.optional(),
  borneByDriverId: uuidSchema.optional(),
  borneByCustomerId: uuidSchema.optional(),
  paidByUserId: uuidSchema.optional(),
  // eslint-disable-next-line no-restricted-syntax -- fuel litres, not money (UC-72)
  litres: z.number().positive().optional(),
  // GAP-30/F-3.3: a fuel fill's own odometer reading, written as a real
  // `odometer_reading` row in the same transaction (INV-19/W-18) — not
  // stored on the expense alone. Needs a vehicle to belong to, and the two
  // fields are given together or not at all, same shape as
  // `bookTripRequestSchema`'s opening reading.
  // eslint-disable-next-line no-restricted-syntax -- an odometer figure, not money
  odometerReadingKm: z.number().int().nonnegative().optional(),
  odometerSource: odometerSourceSchema.optional(),
  note: z.string().trim().max(500).optional(),
});

/**
 * The four cross-field rules create and replace both enforce — generic over
 * any schema whose own output at least carries `expenseCommonFieldsSchema`'s
 * fields, so this applies unchanged to either's own `.extend()`, extra
 * fields (`replacesId`/`reason`) and all.
 */
function withExpenseFieldRules<T extends z.infer<typeof expenseCommonFieldsSchema>>(
  schema: z.ZodType<T>,
) {
  return schema
    .refine((v) => v.borneBy !== "driver" || v.borneByDriverId !== undefined, {
      message: "borneByDriverId is required when borneBy is 'driver'",
      path: ["borneByDriverId"],
    })
    .refine((v) => v.borneBy !== "customer" || v.borneByCustomerId !== undefined, {
      message: "borneByCustomerId is required when borneBy is 'customer'",
      path: ["borneByCustomerId"],
    })
    .refine((v) => (v.odometerReadingKm === undefined) === (v.odometerSource === undefined), {
      message: "odometerReadingKm and odometerSource must be given together",
      path: ["odometerSource"],
    })
    .refine((v) => v.odometerReadingKm === undefined || v.vehicleId !== undefined, {
      message: "vehicleId is required to record an odometer reading",
      path: ["vehicleId"],
    })
    .refine((v) => v.category !== "finance", {
      // Copilot review, PR #183: without this, the generic create/replace
      // endpoint would happily accept a manually supplied `category:
      // "finance"` row unlinked to any loan payment — one `domain/expense.ts`'s
      // own `assertExpenseNotFinanceLinked` guard wouldn't catch (nothing
      // references it), yet `ExpenseCostRow` hides Edit/Void for every
      // `finance` row regardless of linkage, making such a row permanently
      // uneditable through the client. Enforcing the invariant the GAP-185
      // comment already claimed ("never a category a person picks here")
      // here, once, is simpler than teaching the client to check the real
      // loan_payment linkage instead of the category proxy.
      message: "finance is generated by the loan-payment flow, never chosen directly",
      path: ["category"],
    });
}

export const createExpenseRequestSchema = withExpenseFieldRules(
  expenseCommonFieldsSchema.extend({
    // GAP-60/D-16/F-8.5: set when this expense is the corrected replacement
    // for one already voided — the target must belong to this business and
    // already be voided, checked server-side (domain/expense.ts).
    replacesId: uuidSchema.optional(),
  }),
);
export type CreateExpenseRequest = z.infer<typeof createExpenseRequestSchema>;

export const expenseResponseSchema = z.object({
  id: z.string().uuid(),
  vehicleId: z.string().uuid().nullable(),
  tripId: z.string().uuid().nullable(),
  incidentId: z.string().uuid().nullable(),
  category: expenseCategorySchema,
  amountMinor: z.string(),
  spentOn: z.string(),
  borneBy: borneBySchema,
  borneByDriverId: z.string().uuid().nullable(),
  borneByCustomerId: z.string().uuid().nullable(),
  paidByUserId: z.string().uuid().nullable(),
  // eslint-disable-next-line no-restricted-syntax -- fuel litres, not money
  litres: z.number().nullable(),
  // GAP-30/UC-72: the `odometer_reading` row this fill wrote, when it did —
  // `listUsBoughtFuelFills` (queries/reports.ts) is what dereferences this
  // into a km/l figure for the fuel-efficiency report.
  odometerReadingId: z.string().uuid().nullable(),
  // Copilot review, PR #182: the reading itself, not just its id — GAP-224's
  // edit sheet needs the actual km/source to prefill (and re-preserve) a
  // servicing expense's reading rather than silently dropping it on an
  // unrelated correction (`findLastMaintenanceOdometerKm` inner-joins this,
  // so a replacement with no reading vanishes from the maintenance prompt).
  // eslint-disable-next-line no-restricted-syntax -- an odometer figure, not money
  odometerReadingKm: z.number().int().nonnegative().nullable(),
  odometerReadingSource: odometerSourceSchema.nullable(),
  note: z.string().nullable(),
  // GAP-60/D-16/F-8.6: "what corrected this?", answered from the record
  // itself rather than only from a global log.
  replacesId: z.string().uuid().nullable(),
});
export type ExpenseResponse = z.infer<typeof expenseResponseSchema>;

/** Vehicle overview's costs tab (Web-P5): `expenseResponseSchema` plus the void fields — a voided expense stays in the list, struck through with its reason, never removed (W-50). */
export const expenseListRowSchema = expenseResponseSchema.extend({
  voidedAt: z.string().nullable(),
  voidedReason: z.string().nullable(),
});
export type ExpenseListRow = z.infer<typeof expenseListRowSchema>;

export const listExpensesResponseSchema = z.array(expenseListRowSchema);
export type ListExpensesResponse = z.infer<typeof listExpensesResponseSchema>;

/**
 * Web-P8b's costs list (F-3.1): every filter optional — an unfiltered call
 * is every expense the business has ever logged, newest first. `from`/`to`
 * bound `spentOn`, not `createdAt` (an expense entered late is still dated
 * when it happened, same as `insertExpense`'s own doc comment).
 */
export const listExpensesQuerySchema = z.object({
  vehicleId: uuidSchema.optional(),
  tripId: uuidSchema.optional(),
  incidentId: uuidSchema.optional(),
  category: expenseCategorySchema.optional(),
  from: businessDateSchema.optional(),
  to: businessDateSchema.optional(),
});
export type ListExpensesQuery = z.infer<typeof listExpensesQuerySchema>;

/**
 * GAP-32/§6.7: a live preview of the default-owner matrix, resolved against
 * the vehicle's arrangement as of `spentOn` — what `resolveBorneByDefault`
 * (domain/expense.ts) would choose if the record were saved right now. Lets
 * the client show the default before offering an override to a *different*
 * driver or customer, without a second implementation of the matrix.
 */
export const resolveBorneByQuerySchema = z.object({
  vehicleId: uuidSchema,
  category: expenseCategorySchema,
  spentOn: businessDateSchema,
});
export type ResolveBorneByQuery = z.infer<typeof resolveBorneByQuerySchema>;

export const resolveBorneByResponseSchema = z.object({
  borneBy: borneBySchema,
  borneByDriverId: z.string().uuid().nullable(),
  borneByCustomerId: z.string().uuid().nullable(),
});
export type ResolveBorneByResponse = z.infer<typeof resolveBorneByResponseSchema>;

/**
 * GAP-34/U-3: "vehicle defaults to the one with something pending" — no
 * last-touched-vehicle column exists, so this reuses the one concrete
 * "pending" fact already tracked against a vehicle: Home item 4's own
 * unconfirmed-day definition, oldest first. `vehicleId` is `null` when
 * nothing is pending — the caller's own fallback (first vehicle in the
 * list) is unaffected.
 */
export const expensePrefillVehicleResponseSchema = z.object({
  vehicleId: z.string().uuid().nullable(),
});
export type ExpensePrefillVehicleResponse = z.infer<typeof expensePrefillVehicleResponseSchema>;

/** F-8.5/UC-96: "wrong vehicle... fuel logged against the wrong trip" — void it, with a reason, then record the corrected one through the ordinary create endpoint. */
export const voidExpenseRequestSchema = z.object({
  reason: z.string().trim().min(1).max(500),
});
export type VoidExpenseRequest = z.infer<typeof voidExpenseRequestSchema>;

export const voidedExpenseResponseSchema = z.object({
  id: uuidSchema,
  voidedAt: z.string(),
});
export type VoidedExpenseResponse = z.infer<typeof voidedExpenseResponseSchema>;

/**
 * GAP-224/F-8.5: "Edit" on the client, void-and-replace underneath — the
 * wire shape is one request either way (`PATCH /api/expense/{id}`), and the
 * word "void" never reaches the manager. Same shared field set as
 * `createExpenseRequestSchema`, plus `reason`, required — a money
 * correction never has an optional one (F-8.5's own Accept clause;
 * migration 0025's `replaces_id` unique index is the constraint half, this
 * is the input half). `replacesId` has no place here: the server sets it
 * to the id in the path, the same way `void`'s own reason doesn't let the
 * caller name a different target than the URL.
 */
export const replaceExpenseRequestSchema = withExpenseFieldRules(
  expenseCommonFieldsSchema.extend({
    reason: z.string().trim().min(1).max(500),
  }),
);
export type ReplaceExpenseRequest = z.infer<typeof replaceExpenseRequestSchema>;
